version: "3.9"

services:
  # -------------------- BACKEND --------------------
  backend:
    build: ./backend
    container_name: infinityai-backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data:/app/data
      - ./backend/models:/app/models
      - ./backend/trade_logs:/app/trade_logs
      - ./backend/chroma_db:/app/chroma_db
    environment:
      - VECTOR_DB_URL=http://vectordb:8000
    depends_on:
      - vectordb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # -------------------- FRONTEND --------------------
  frontend:
    build: ./frontend
    container_name: infinityai-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8000

  # -------------------- VECTOR DB --------------------
  vectordb:
    image: chromadb/chroma:latest
    container_name: infinityai-vectordb
    restart: unless-stopped
    ports:
      - "8001:8000"
    volumes:
      - chroma_data:/chroma
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000

volumes:
  chroma_data: