steps:
  # --- ENGINE C ONLY ---
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-engine-c'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/project-841b7f97-5ee3-4fbe-920/cloud-run-source-deploy/engine-c:latest', '-f', 'backend/engine-c/Dockerfile', '.']
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-engine-c'
    args: ['push', 'asia-south1-docker.pkg.dev/project-841b7f97-5ee3-4fbe-920/cloud-run-source-deploy/engine-c:latest']
    waitFor: ['build-engine-c']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-engine-c'
    entrypoint: gcloud
    args: ['run', 'deploy', 'engine-c', '--image', 'asia-south1-docker.pkg.dev/project-841b7f97-5ee3-4fbe-920/cloud-run-source-deploy/engine-c:latest', '--set-env-vars', 'GOOGLE_CLOUD_PROJECT=project-841b7f97-5ee3-4fbe-920', '--region', 'asia-south1']
    waitFor: ['push-engine-c']

images:
  - 'asia-south1-docker.pkg.dev/project-841b7f97-5ee3-4fbe-920/cloud-run-source-deploy/engine-c:latest'
