steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "asia-south1-docker.pkg.dev/project-841b7f97-5ee3-4fbe-920/infinityai/engine-b",
        "-f",
        "engine-b/Dockerfile",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "asia-south1-docker.pkg.dev/project-841b7f97-5ee3-4fbe-920/infinityai/engine-c",
        "-f",
        "engine-c/Dockerfile",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "asia-south1-docker.pkg.dev/project-841b7f97-5ee3-4fbe-920/infinityai/engine-a",
        "-f",
        "engine-a/Dockerfile",
        ".",
      ]
images:
  - "asia-south1-docker.pkg.dev/project-841b7f97-5ee3-4fbe-920/infinityai/engine-b"
  - "asia-south1-docker.pkg.dev/project-841b7f97-5ee3-4fbe-920/infinityai/engine-c"
  - "asia-south1-docker.pkg.dev/project-841b7f97-5ee3-4fbe-920/infinityai/engine-a"
