steps:
  # Build Engine A
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'backend'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/engine-a', '-f', 'engine-a/Dockerfile', '.']
  
  # Build Engine B
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'backend'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/engine-b', '-f', 'engine-b/Dockerfile', '.']

  # Build Engine C
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'backend'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/engine-c', '-f', 'engine-c/Dockerfile', '.']

images:
  - 'gcr.io/$PROJECT_ID/engine-a'
  - 'gcr.io/$PROJECT_ID/engine-b'
  - 'gcr.io/$PROJECT_ID/engine-c'
