services:
  # =========================
  # FRONTEND (React)
  # =========================
  - type: web
    name: infinityai-frontend
    env: node
    repo: https://github.com/raghu-1718/InfinityAI.Pro
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm install -g serve && serve -s build -l 10000
    rootDir: infinityai-pro/frontend
    envVars:
      - key: REACT_APP_API_URL
        value: https://api.infinityai.pro

  # =========================
  # BACKEND (FastAPI)
  # =========================
  - type: web
    name: infinityai-backend
    env: docker
    repo: https://github.com/raghu-1718/InfinityAI.Pro
    branch: main
    rootDir: infinityai-pro/backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: RUNPOD_SD_ENDPOINT
        value: https://ga4sxq6i6mrw72-8888.proxy.runpod.net
      - key: RUNPOD_YOLO_ENDPOINT
        value: https://s2415wou493ooq-8888.proxy.runpod.net
      - key: RUNPOD_WHISPER_ENDPOINT
        value: https://wmca1dz5qqm7kn-8888.proxy.runpod.net
      - key: RUNPOD_API_KEY
        sync: false
      - key: HUGGINGFACE_API_KEY
        sync: false
      - key: DHAN_CLIENT_ID
        sync: false
      - key: DHAN_ACCESS_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: ALPHA_VANTAGE_API_KEY
        value: BD03X0M5F86UW8PP
      - key: OLLAMA_BASE_URL
        value: http://ollama:11434
      - key: CHROMA_HOST
        value: chroma
      - key: CHROMA_PORT
        value: 8000
      - key: DATABASE_URL
        value: sqlite:///./chroma_db/chroma.sqlite3

  # =========================
  # OLLAMA (LLMs)
  # =========================
  - type: pserv
    name: ollama
    env: docker
    repo: https://github.com/raghu-1718/InfinityAI.Pro
    branch: main
    rootDir: infinityai-pro/ollama
    dockerfilePath: ./Dockerfile
    plan: standard
    envVars:
      - key: OLLAMA_HOST
        value: 0.0.0.0
      - key: OLLAMA_PORT
        value: 11434

  # =========================
  # CHROMADB (Vector DB)
  # =========================
  - type: pserv
    name: chroma
    env: docker
    repo: https://github.com/raghu-1718/InfinityAI.Pro
    branch: main
    rootDir: infinityai-pro/chroma
    dockerfilePath: ./Dockerfile
    disk:
      name: chroma-data
      mountPath: /data
      sizeGB: 20
    envVars:
      - key: CHROMA_HOST
        value: 0.0.0.0
      - key: CHROMA_PORT
        value: 8000