apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/client-name: gcloud
    run.googleapis.com/client-version: 544.0.0
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/maxScale: '3'
    run.googleapis.com/operation-id: 71bc678a-49dc-49e9-b9c8-e6f46ecbbfb9
    run.googleapis.com/urls: '["https://engine-a-228557716858.us-central1.run.app","https://engine-a-3acobgd3qa-uc.a.run.app"]'
    serving.knative.dev/creator: arunagopi99@gmail.com
    serving.knative.dev/lastModifier: arunagopi99@gmail.com
  creationTimestamp: '2026-01-04T16:56:47.669903Z'
  generation: 32
  labels:
    cloud.googleapis.com/location: us-central1
  name: engine-a
  namespace: '228557716858'
  resourceVersion: AAZIW4OA6QE
  selfLink: /apis/serving.knative.dev/v1/namespaces/228557716858/services/engine-a
  uid: 32ba66b5-47fa-4b97-9fdf-1edd95fc298c
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '5'
        autoscaling.knative.dev/minScale: '1'
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 544.0.0
        run.googleapis.com/cpu-throttling: 'false'
        run.googleapis.com/startup-cpu-boost: 'true'
      labels:
        client.knative.dev/nonce: kgigzzzpsh
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 80
      containers:
      - env:
        - name: GOOGLE_CLOUD_PROJECT
          value: project-841b7f97-5ee3-4fbe-920
        - name: ENGINE_B_URL
          value: https://engine-b-3acobgd3qa-uc.a.run.app
        - name: ENGINE_C_URL
          value: https://engine-c-3acobgd3qa-uc.a.run.app
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: cloudtrace.googleapis.com:443
        - name: USER_ID
          value: B79BqvTlaTZltC8uGO3jLxJBBt93
        - name: FORCE_UPDATE
          value: "true"
        - name: DHAN_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: latest
              name: dhan-client-id
        - name: DHAN_API_SECRET
          valueFrom:
            secretKeyRef:
              key: latest
              name: dhan-api-secret
        - name: DHAN_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              key: latest
              name: dhan-access-token
        image: us-central1-docker.pkg.dev/project-841b7f97-5ee3-4fbe-920/infinityai/engine-a:latest
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: '1'
            memory: 1Gi
      serviceAccountName: engine-a-sa@project-841b7f97-5ee3-4fbe-920.iam.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
status:
  address:
    url: https://engine-a-3acobgd3qa-uc.a.run.app
  conditions:
  - lastTransitionTime: '2026-01-14T16:22:25.751297Z'
    status: 'True'
    type: Ready
  - lastTransitionTime: '2026-01-14T16:22:02.761763Z'
    status: 'True'
    type: ConfigurationsReady
  - lastTransitionTime: '2026-01-14T16:22:25.709315Z'
    status: 'True'
    type: RoutesReady
  latestCreatedRevisionName: engine-a-00032-vq8
  latestReadyRevisionName: engine-a-00032-vq8
  observedGeneration: 32
  traffic:
  - latestRevision: true
    percent: 100
    revisionName: engine-a-00032-vq8
  url: https://engine-a-3acobgd3qa-uc.a.run.app
