services:
  engine-analytics:
    build:
      context: ./engine-analytics
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      - ENGINE_B_URL=http://engine-core:8000
      - ENGINE_C_URL=http://engine-execution:8000
    volumes:
      - ./engine-analytics/src:/app/src

  engine-core:
    build:
      context: ./engine-core
      dockerfile: Dockerfile
    volumes:
      - ./engine-core/src:/app/src
      - ./strategies:/app/src/strategies

  engine-execution:
    build:
      context: ./engine-execution
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./engine-execution/src:/app/src

