# Base image
FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Copy requirements and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the specific engine script
COPY autonomous_trader.py .

# Command to run the engine
CMD ["python", "./autonomous_trader.py"]
