name: Build & Deploy Engine
on:
  push:
    branches: [ main ]
    paths:
      - "engine/**"
      - "shared/**"
      - "config/**"
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/tradingai-engine:latest ./engine
          docker push ghcr.io/${{ github.repository_owner }}/tradingai-engine:latest

  deploy-northflank:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Northflank deploy
        run: |
          curl -X POST https://api.northflank.com/v1/deployments \
            -H "Authorization: Bearer ${{ secrets.NORTHFLANK_API_TOKEN }}" \
            -H "Content-Type": application/json" \
            -d '{"service":"tradingai-engine","image":"ghcr.io/'"${{ github.repository_owner }}"'/tradingai-engine:latest"}'
