name: Deploy to Vercel
on:
  push:
    branches: [ main ]
    paths:
      - "api-webhooks/**"
      - "shared/**"
      - "config/**"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Sync env to build (optional)
        run: cp config/.env.example .env || true

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          npm i -g vercel
          cd api-webhooks
          vercel deploy --prod --yes
