steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/project-841b7f97-5ee3-4fbe-920/infinityai-engine-b:latest', '-f', 'backend/engine-b/Dockerfile', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/project-841b7f97-5ee3-4fbe-920/infinityai-engine-b:latest']
images:
- 'gcr.io/project-841b7f97-5ee3-4fbe-920/infinityai-engine-b:latest'