steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/galvanic-pulsar-482815-h0/infinityai/engine-b:latest",
        "-f",
        "engine-b/Dockerfile",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/galvanic-pulsar-482815-h0/infinityai/engine-b:latest",
      ]

images:
  - "us-central1-docker.pkg.dev/galvanic-pulsar-482815-h0/infinityai/engine-b:latest"
