steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/gen-lang-client-0779271931/infinityai-engine-b:latest', '-f', 'backend/engine-b/Dockerfile', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/gen-lang-client-0779271931/infinityai-engine-b:latest']
images:
- 'gcr.io/gen-lang-client-0779271931/infinityai-engine-b:latest'