steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/infinity-ai-5ec7c/infinityai-engine-b:latest', '-f', 'backend/engines/engine-b/Dockerfile', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/infinity-ai-5ec7c/infinityai-engine-b:latest']
images:
- 'gcr.io/infinity-ai-5ec7c/infinityai-engine-b:latest'