import os
import uuid
import logging
from google.cloud import dialogflowcx_v3 as dialogflow

logger = logging.getLogger("InfinityAI.ManagedBQAgent")

class ManagedBigQueryAgent:
    def __init__(self):
        self.project_id = "project-841b7f97-5ee3-4fbe-920"
        self.location = "global"
        self.agent_id = "ba07e608-4afd-4cde-9142-2086f4747986"
        self.language_code = "en"

    def ask_agent(self, text_query: str, session_id: str = None) -> dict:
        try:
            # Generate a random session ID if not provided, allowing for conversational memory
            if not session_id:
                session_id = str(uuid.uuid4())

            client_options = None
            if self.location != "global":
                api_endpoint = f"{self.location}-dialogflow.googleapis.com:443"
                client_options = {"api_endpoint": api_endpoint}

            client = dialogflow.SessionsClient(client_options=client_options)
            session_path = f"projects/{self.project_id}/locations/{self.location}/agents/{self.agent_id}/sessions/{session_id}"

            text_input = dialogflow.TextInput(text=text_query)
            query_input = dialogflow.QueryInput(text=text_input, language_code=self.language_code)

            request = dialogflow.DetectIntentRequest(
                session=session_path,
                query_input=query_input
            )

            logger.info(f"🚀 Sending query to GCP Agent: {text_query}")
            response = client.detect_intent(request=request)

            # Extract the natural language response generated by your agent
            if response.query_result.response_messages:
                reply = response.query_result.response_messages[0].text.text[0]
            else:
                reply = "No response generated by the agent."

            return {
                "status": "success",
                "session_id": session_id,
                "query": text_query,
                "agent_reply": reply
            }

        except Exception as e:
            logger.error(f"❌ GCP Managed Agent Error: {e}")
            return {"status": "error", "message": str(e)}
