
name: Deploy Engine C to Cloud Run

on:
  push:
    branches:
      - main
    paths:
      - 'engine-c/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 'Deploy to Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: 'engine-c-execution-prod'
          source: './engine-c'
          region: 'us-central1'
