name: Deploy Engine D

on:
  push:
    branches:
      - main
    paths:
      - "backend/engine-d/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: GCP Auth
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}"

      - name: Deploy to Cloud Run
        uses: "google-github-actions/deploy-cloudrun@v1"
        with:
          service: infinityai-engine-d
          region: us-central1
          source: ./backend/engine-d/src
          project_id: infinity-ai-5ec7c

