name: Trigger auto deployment for infinityai-engine-a

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/infinityai-engine-a-AutoDeployTrigger-3cad2f5b-35e1-4bf7-ae56-17626933b958.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.INFINITYAIENGINEA_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.INFINITYAIENGINEA_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.INFINITYAIENGINEA_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: infinityaiacr.azurecr.io
          registryUsername: ${{ secrets.INFINITYAIENGINEA_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.INFINITYAIENGINEA_REGISTRY_PASSWORD }}
          containerAppName: infinityai-engine-a
          resourceGroup: infinityai-pro-rg
          imageToBuild: infinityaiacr.azurecr.io/infinityai-engine-a:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


